1. Удалил файл model.py в dds-service (подумал, что нужно использовать pydantic 
  для валидации передаваемых данных, но в итоге не стал)
2. Убрал лишний комментарий в dds_message_processor_job.py
